services:
  app:
    build:
      context: .
      args:
        JESUS_PASSWORD: ${JESUS_PASSWORD}
        IKER_PASSWORD: ${IKER_PASSWORD}
    container_name: TelegramBot
    restart: always
    hostname: yharnam
    env_file:
      - .env
    volumes:
      - ../Bot/:/usr/src/app/workspace
    stdin_open: true
    tty: true
    user: "jesus"